#options:
#  preGenCommand: N/A
#  postGenCommand: N/A
  
include:
  - path: /Users/theochen/.tooling/xcodegen/base.yml

name: Example
settings:
  groups:
    - BaseProjectSetting
    
packages:
  RouteFoundation:
    path: ../../
  Product:
    path: ../Features/Product
  Home:
    path: ../Features/Home

targets:

  RouteFoundationExample:
    type: application
    platform: iOS
    sources: [
      ../../RouteFoundation
    ]
    scheme: {} # Generates default scheme
    dependencies:
      - package: RouteFoundation
      - package: Product
      - package: Home
    postCompileScripts:
    - script: "\
SDKROOT=(xcrun --sdk macosx --show-sdk-path)\n\
SWIFTLINT_YML=$HOME/.tooling/swiftlint/base.yml\n\
PATH=/opt/homebrew/bin:$PATH\n\
\n\
if [ -f $SWIFTLINT_YML ]; then\n\
  if which swiftlint >/dev/null; then\n\
    swiftlint --no-cache --config $SWIFTLINT_YML --path ../../ --reporter xcode\n\
  fi\n\
else\n\
  printf 'Not found .swiftlnt.yml'\n\
  exit 0\n\
fi\
"
    settings:
      groups:
        - BaseTargetSetting
      base:
        PRODUCT_BUNDLE_IDENTIFIER: codes.codebase.route-foundation
        #ASSETCATALOG_COMPILER_APPICON_NAME: appicon_dark
        #APPCENTER_APP_SECRET: The secret is set by CI server
        #CODE_SIGN_ENTITLEMENTS: autogenerated.entitlements
        DEVELOPMENT_TEAM: 32T9S8EBKN
#      configFiles:
#        Debug: ----/debug.xcconfig
#        Release: ----/release.xcconfig
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Manual
          #PROVISIONING_PROFILE_SPECIFIER: "match AppStore "
          CODE_SIGN_IDENTITY: "Apple Distribution"
